//@GeneratedCode
namespace QTPriceChecker.WebApi.Models.App
{
    using System;
    ///
    /// Generated by the generator
    ///
    public partial class PriceHistoryEdit
    {
        ///
        /// Generated by the generator
        ///
        static PriceHistoryEdit()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        ///
        /// Generated by the generator
        ///
        public PriceHistoryEdit()
        {
            Constructing();
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public System.Int32 ProductXSupplierId
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public System.DateTime From
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public System.Decimal Price
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public QTPriceChecker.WebApi.Models.Base.ProductXSupplier? ProductXSupplier
        {
            get;
            set;
        }
    }
}
