//@GeneratedCode
namespace QTPriceChecker.WebApi.Controllers.App
{
    ///
    /// Generated by the generator
    ///
    public sealed partial class PriceHistoriesController : Controllers.GenericController<QTPriceChecker.Logic.Entities.App.PriceHistory, QTPriceChecker.WebApi.Models.App.PriceHistoryEdit, QTPriceChecker.WebApi.Models.App.PriceHistory>
    {
        ///
        /// Generated by the generator
        ///
        static PriceHistoriesController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        ///
        /// Generated by the generator
        ///
        public PriceHistoriesController(QTPriceChecker.Logic.Contracts.App.IPriceHistoriesAccess<QTPriceChecker.Logic.Entities.App.PriceHistory> other)
        : base(other)
        {
            Constructing();
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        protected override QTPriceChecker.WebApi.Models.App.PriceHistory ToOutModel(QTPriceChecker.Logic.Entities.App.PriceHistory accessModel)
        {
            var handled = false;
            var result = default(QTPriceChecker.WebApi.Models.App.PriceHistory);
            BeforeToOutModel(accessModel, ref result, ref handled);
            if (handled == false || result == null)
            {
                result = QTPriceChecker.WebApi.Models.App.PriceHistory.Create(accessModel);
            }
            AfterToOutModel(result);
            return result;
        }
        partial void BeforeToOutModel(QTPriceChecker.Logic.Entities.App.PriceHistory accessModel, ref QTPriceChecker.WebApi.Models.App.PriceHistory? outModel, ref bool handled);
        partial void AfterToOutModel(QTPriceChecker.WebApi.Models.App.PriceHistory outModel);
    }
}
