//@CodeCopy
//MdStart
#if ACCOUNT_ON
namespace QTPriceChecker.WebApi.Controllers.Account
{
    using TAccessModel = QTPriceChecker.Logic.Models.Account.Role;
    using TEditModel = QTPriceChecker.WebApi.Models.Account.AccessRoleEdit;
    using TOutModel = QTPriceChecker.WebApi.Models.Account.AccessRole;
    ///
    /// Generated by the generator
    ///
    public sealed partial class AccessRolesController : Controllers.GenericController<TAccessModel, TEditModel, TOutModel>
    {
        ///
        /// Generated by the generator
        ///
        static AccessRolesController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        ///
        /// Generated by the generator
        ///
        public AccessRolesController(QTPriceChecker.Logic.Contracts.Account.IRolesAccess<TAccessModel> other)
        : base(other)
        {
            Constructing();
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        protected override TOutModel ToOutModel(TAccessModel accessModel)
        {
            var handled = false;
            var result = default(TOutModel);
            BeforeToOutModel(accessModel, ref result, ref handled);
            if (handled == false || result == null)
            {
                result = TOutModel.Create(accessModel);
            }
            AfterToOutModel(result);
            return result;
        }
        partial void BeforeToOutModel(TAccessModel accessModel, ref TOutModel? outModel, ref bool handled);
        partial void AfterToOutModel(TOutModel outModel);
    }
}
#endif
//MdEnd
