//@GeneratedCode
namespace QTPriceChecker.Logic.Contracts.Base
{
    ///
    /// Generated by the generator
    ///
    public partial interface IProductXSuppliersAccess<T> : Contracts.IDataAccess<T>
    {
    }
}
