//@GeneratedCode
namespace QTPriceChecker.AspMvc.Models.App
{
    using System;
    ///
    /// Generated by the generator
    ///
    public partial class PriceHistoryFilter : Models.View.IFilterModel
    {
        ///
        /// Generated by the generator
        ///
        static PriceHistoryFilter()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        ///
        /// Generated by the generator
        ///
        public PriceHistoryFilter()
        {
            Constructing();
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public System.Int32? SupplierXProductId
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public System.DateTime? From
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public System.Decimal? Price
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public bool HasEntityValue => SupplierXProductId != null || From != null || Price != null;
        private bool show = true;
        ///
        /// Generated by the generator
        ///
        public bool Show => show;
        ///
        /// Generated by the generator
        ///
        public string CreateEntityPredicate()
        {
            var result = new System.Text.StringBuilder();
            if (SupplierXProductId != null)
            {
                if (result.Length > 0)
                {
                    result.Append(" || ");
                }
                result.Append($"(SupplierXProductId != null && SupplierXProductId == {SupplierXProductId})");
            }
            if (From != null)
            {
                if (result.Length > 0)
                {
                    result.Append(" || ");
                }
                result.Append($"(From != null && From == {From})");
            }
            if (Price != null)
            {
                if (result.Length > 0)
                {
                    result.Append(" || ");
                }
                result.Append($"(Price != null && Price == {Price})");
            }
            return result.ToString();
        }
        ///
        /// Generated by the generator
        ///
        public override string ToString()
        {
            return $"SupplierXProductId: {(SupplierXProductId != null ? SupplierXProductId : "---")} From: {(From != null ? From : "---")} Price: {(Price != null ? Price : "---")} ";
        }
    }
}
