//@GeneratedCode
namespace QTPriceChecker.WebApi.Models.Base
{
    using System;
    ///
    /// Generated by the generator
    ///
    public partial class ProductEdit
    {
        ///
        /// Generated by the generator
        ///
        static ProductEdit()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        ///
        /// Generated by the generator
        ///
        public ProductEdit()
        {
            Constructing();
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public System.String Number
        {
            get;
            set;
        }
        = string.Empty;
        ///
        /// Generated by the generator
        ///
        public System.String Designation
        {
            get;
            set;
        }
        = string.Empty;
        ///
        /// Generated by the generator
        ///
        public System.String? Description
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public System.Double Quantity
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public QTPriceChecker.Logic.Modules.Common.UnitOfMeasure Unit
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public System.Decimal CurrenPrice
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public QTPriceChecker.Logic.Modules.Common.State State
        {
            get;
            set;
        }
    }
}
