//@GeneratedCode
namespace QTPriceChecker.WebApi.Models.Base
{
    using System;
    ///
    /// Generated by the generator
    ///
    public partial class SupplierXProduct
    {
        ///
        /// Generated by the generator
        ///
        static SupplierXProduct()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        ///
        /// Generated by the generator
        ///
        public SupplierXProduct()
        {
            Constructing();
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public System.Int32 SupplierId
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public System.Int32 ProductId
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public System.Decimal CurrentPrice
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public QTPriceChecker.WebApi.Models.Base.Supplier? Supplier
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public QTPriceChecker.WebApi.Models.Base.Product? Product
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public System.Collections.Generic.List<QTPriceChecker.WebApi.Models.App.PriceHistory> PriceHistories
        {
            get;
            set;
        }
        = new();
        ///
        /// Generated by the generator
        ///
        public static QTPriceChecker.WebApi.Models.Base.SupplierXProduct Create()
        {
            BeforeCreate();
            var result = new QTPriceChecker.WebApi.Models.Base.SupplierXProduct();
            AfterCreate(result);
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public static QTPriceChecker.WebApi.Models.Base.SupplierXProduct Create(object other)
        {
            BeforeCreate(other);
            CommonBase.Extensions.ObjectExtensions.CheckArgument(other, nameof(other));
            var result = new QTPriceChecker.WebApi.Models.Base.SupplierXProduct();
            CommonBase.Extensions.ObjectExtensions.CopyFrom(result, other);
            AfterCreate(result, other);
            return result;
        }
        static partial void BeforeCreate();
        static partial void AfterCreate(QTPriceChecker.WebApi.Models.Base.SupplierXProduct instance);
        static partial void BeforeCreate(object other);
        static partial void AfterCreate(QTPriceChecker.WebApi.Models.Base.SupplierXProduct instance, object other);
        ///
        /// Generated by the generator
        ///
        public static QTPriceChecker.WebApi.Models.Base.SupplierXProduct Create(QTPriceChecker.Logic.Entities.Base.SupplierXProduct other)
        {
            BeforeCreate(other);
            var result = new QTPriceChecker.WebApi.Models.Base.SupplierXProduct();
            result.CopyProperties(other);
            AfterCreate(result, other);
            return result;
        }
        static partial void BeforeCreate(QTPriceChecker.Logic.Entities.Base.SupplierXProduct other);
        static partial void AfterCreate(QTPriceChecker.WebApi.Models.Base.SupplierXProduct instance, QTPriceChecker.Logic.Entities.Base.SupplierXProduct other);
        ///
        /// Generated by the generator
        ///
        public void CopyProperties(QTPriceChecker.Logic.Entities.Base.SupplierXProduct other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                SupplierId = other.SupplierId;
                ProductId = other.ProductId;
                CurrentPrice = other.CurrentPrice;
                Supplier = other.Supplier != null ? QTPriceChecker.WebApi.Models.Base.Supplier.Create((object)other.Supplier) : null;
                Product = other.Product != null ? QTPriceChecker.WebApi.Models.Base.Product.Create((object)other.Product) : null;
                PriceHistories = other.PriceHistories.Select(e => QTPriceChecker.WebApi.Models.App.PriceHistory.Create((object)e)).ToList();
                RowVersion = other.RowVersion;
                Id = other.Id;
            }
            AfterCopyProperties(other);
        }
        partial void BeforeCopyProperties(QTPriceChecker.Logic.Entities.Base.SupplierXProduct other, ref bool handled);
        partial void AfterCopyProperties(QTPriceChecker.Logic.Entities.Base.SupplierXProduct other);
        ///
        /// Generated by the generator
        ///
        public void CopyProperties(QTPriceChecker.WebApi.Models.Base.SupplierXProduct other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                SupplierId = other.SupplierId;
                ProductId = other.ProductId;
                CurrentPrice = other.CurrentPrice;
                Supplier = other.Supplier;
                Product = other.Product;
                PriceHistories = other.PriceHistories;
                RowVersion = other.RowVersion;
                Id = other.Id;
            }
            AfterCopyProperties(other);
        }
        partial void BeforeCopyProperties(QTPriceChecker.WebApi.Models.Base.SupplierXProduct other, ref bool handled);
        partial void AfterCopyProperties(QTPriceChecker.WebApi.Models.Base.SupplierXProduct other);
        ///
        /// Generated by the generator
        ///
        public override bool Equals(object? obj)
        {
            bool result = false;
            if (obj is Models.Base.SupplierXProduct other)
            {
                result = IsEqualsWith(RowVersion, other.RowVersion)
                && Id == other.Id;
            }
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public override int GetHashCode()
        {
            return HashCode.Combine(SupplierId, ProductId, CurrentPrice, Supplier, Product, PriceHistories, HashCode.Combine(RowVersion, Id));
        }
    }
}
