//@GeneratedCode
namespace QTPriceChecker.WebApi.Models.Base
{
    using System;
    ///
    /// Generated by the generator
    ///
    public partial class SupplierEdit
    {
        ///
        /// Generated by the generator
        ///
        static SupplierEdit()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        ///
        /// Generated by the generator
        ///
        public SupplierEdit()
        {
            Constructing();
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public System.String Name
        {
            get;
            set;
        }
        = string.Empty;
        ///
        /// Generated by the generator
        ///
        public QTPriceChecker.Logic.Modules.Common.State State
        {
            get;
            set;
        }
    }
}
