//@GeneratedCode
namespace QTPriceChecker.Logic.Models.Base
{
    using System;
    ///
    /// Generated by the generator
    ///
    public partial class Product
    {
        ///
        /// Generated by the generator
        ///
        static Product()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        ///
        /// Generated by the generator
        ///
        public Product()
        {
            Constructing();
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        new internal QTPriceChecker.Logic.Entities.Base.Product Source
        {
            get => (QTPriceChecker.Logic.Entities.Base.Product)(_source ??= new QTPriceChecker.Logic.Entities.Base.Product());
            set => _source = value;
        }
        public System.String Number
        {
            get => Source.Number;
            set => Source.Number = value;
        }
        public System.String Designation
        {
            get => Source.Designation;
            set => Source.Designation = value;
        }
        public System.String? Description
        {
            get => Source.Description;
            set => Source.Description = value;
        }
        public System.Double Quantity
        {
            get => Source.Quantity;
            set => Source.Quantity = value;
        }
        public QTPriceChecker.Logic.Modules.Common.UnitOfMeasure Unit
        {
            get => Source.Unit;
            set => Source.Unit = value;
        }
        public System.Decimal MinPrice
        {
            get => Source.MinPrice;
        }
        public System.Decimal MaxPrice
        {
            get => Source.MaxPrice;
        }
        public QTPriceChecker.Logic.Modules.Common.State State
        {
            get => Source.State;
            set => Source.State = value;
        }
        public System.Collections.Generic.List<QTPriceChecker.Logic.Models.Base.ProductXSupplier> ProductXSuppliers
        {
            get => Source.ProductXSuppliers.Select(e => QTPriceChecker.Logic.Models.Base.ProductXSupplier.Create(e)).ToList();
            set => Source.ProductXSuppliers = value.Select(e => e.Source).ToList();
        }
        ///
        /// Generated by the generator
        ///
        internal void CopyProperties(QTPriceChecker.Logic.Entities.Base.Product other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                Number = other.Number;
                Designation = other.Designation;
                Description = other.Description;
                Quantity = other.Quantity;
                Unit = other.Unit;
                State = other.State;
                ProductXSuppliers = other.ProductXSuppliers.Select(e => QTPriceChecker.Logic.Models.Base.ProductXSupplier.Create((object)e)).ToList();
                RowVersion = other.RowVersion;
                Id = other.Id;
            }
            AfterCopyProperties(other);
        }
        partial void BeforeCopyProperties(QTPriceChecker.Logic.Entities.Base.Product other, ref bool handled);
        partial void AfterCopyProperties(QTPriceChecker.Logic.Entities.Base.Product other);
        ///
        /// Generated by the generator
        ///
        public void CopyProperties(QTPriceChecker.Logic.Models.Base.Product other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                Number = other.Number;
                Designation = other.Designation;
                Description = other.Description;
                Quantity = other.Quantity;
                Unit = other.Unit;
                State = other.State;
                ProductXSuppliers = other.ProductXSuppliers;
                RowVersion = other.RowVersion;
                Id = other.Id;
            }
            AfterCopyProperties(other);
        }
        partial void BeforeCopyProperties(QTPriceChecker.Logic.Models.Base.Product other, ref bool handled);
        partial void AfterCopyProperties(QTPriceChecker.Logic.Models.Base.Product other);
        ///
        /// Generated by the generator
        ///
        public override bool Equals(object? obj)
        {
            bool result = false;
            if (obj is Models.Base.Product other)
            {
                result = IsEqualsWith(RowVersion, other.RowVersion)
                && Id == other.Id;
            }
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public override int GetHashCode()
        {
            return HashCode.Combine(Number, Designation, Description, Quantity, Unit, MinPrice, HashCode.Combine(MaxPrice, State, ProductXSuppliers, RowVersion, Id));
        }
        ///
        /// Generated by the generator
        ///
        public static QTPriceChecker.Logic.Models.Base.Product Create()
        {
            BeforeCreate();
            var result = new QTPriceChecker.Logic.Models.Base.Product();
            AfterCreate(result);
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public static QTPriceChecker.Logic.Models.Base.Product Create(object other)
        {
            BeforeCreate(other);
            CommonBase.Extensions.ObjectExtensions.CheckArgument(other, nameof(other));
            var result = new QTPriceChecker.Logic.Models.Base.Product();
            CommonBase.Extensions.ObjectExtensions.CopyFrom(result, other);
            AfterCreate(result, other);
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public static QTPriceChecker.Logic.Models.Base.Product Create(QTPriceChecker.Logic.Models.Base.Product other)
        {
            BeforeCreate(other);
            var result = new QTPriceChecker.Logic.Models.Base.Product();
            result.CopyProperties(other);
            AfterCreate(result, other);
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public static QTPriceChecker.Logic.Models.Base.Product Create(QTPriceChecker.Logic.Entities.Base.Product other)
        {
            BeforeCreate(other);
            var result = new QTPriceChecker.Logic.Models.Base.Product();
            result.Source = other;
            AfterCreate(result, other);
            return result;
        }
        static partial void BeforeCreate();
        static partial void AfterCreate(QTPriceChecker.Logic.Models.Base.Product instance);
        static partial void BeforeCreate(object other);
        static partial void AfterCreate(QTPriceChecker.Logic.Models.Base.Product instance, object other);
        static partial void BeforeCreate(QTPriceChecker.Logic.Models.Base.Product other);
        static partial void AfterCreate(QTPriceChecker.Logic.Models.Base.Product instance, QTPriceChecker.Logic.Models.Base.Product other);
        static partial void BeforeCreate(QTPriceChecker.Logic.Entities.Base.Product other);
        static partial void AfterCreate(QTPriceChecker.Logic.Models.Base.Product instance, QTPriceChecker.Logic.Entities.Base.Product other);
    }
}
