//@GeneratedCode
namespace QTPriceChecker.Logic.Controllers.Base
{
    ///
    /// Generated by the generator
    ///
    public sealed partial class ProductsController : Controllers.GenericController<Entities.Base.Product>, Contracts.Base.IProductsAccess<Entities.Base.Product>
    {
        ///
        /// Generated by the generator
        ///
        static ProductsController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        ///
        /// Generated by the generator
        ///
        public ProductsController()
        {
            Constructing();
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public ProductsController(ControllerObject other)
        : base(other)
        {
            Constructing();
            Constructed();
        }
    }
}
