//@GeneratedCode
namespace QTPriceChecker.Logic.Controllers.Base
{
    ///
    /// Generated by the generator
    ///
    public sealed partial class ProductXSuppliersController : Controllers.GenericController<Entities.Base.ProductXSupplier>, Contracts.Base.IProductXSuppliersAccess<Entities.Base.ProductXSupplier>
    {
        ///
        /// Generated by the generator
        ///
        static ProductXSuppliersController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        ///
        /// Generated by the generator
        ///
        public ProductXSuppliersController()
        {
            Constructing();
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public ProductXSuppliersController(ControllerObject other)
        : base(other)
        {
            Constructing();
            Constructed();
        }
    }
}
