//@GeneratedCode
namespace QTPriceChecker.Logic.Controllers.Base
{
    ///
    /// Generated by the generator
    ///
    public sealed partial class SuppliersController : Controllers.GenericController<Entities.Base.Supplier>, Contracts.Base.ISuppliersAccess<Entities.Base.Supplier>
    {
        ///
        /// Generated by the generator
        ///
        static SuppliersController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        ///
        /// Generated by the generator
        ///
        public SuppliersController()
        {
            Constructing();
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public SuppliersController(ControllerObject other)
        : base(other)
        {
            Constructing();
            Constructed();
        }
    }
}
