//@GeneratedCode
namespace QTPriceChecker.Logic.Controllers.Base
{
    ///
    /// Generated by the generator
    ///
    public sealed partial class SupplierXProductsController : Controllers.GenericController<Entities.Base.SupplierXProduct>, Contracts.Base.ISupplierXProductsAccess<Entities.Base.SupplierXProduct>
    {
        ///
        /// Generated by the generator
        ///
        static SupplierXProductsController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        ///
        /// Generated by the generator
        ///
        public SupplierXProductsController()
        {
            Constructing();
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public SupplierXProductsController(ControllerObject other)
        : base(other)
        {
            Constructing();
            Constructed();
        }
    }
}
