//@GeneratedCode
namespace QTPriceChecker.Logic.Contracts.App
{
    ///
    /// Generated by the generator
    ///
    public partial interface IPriceHistoriesAccess<T> : Contracts.IDataAccess<T>
    {
    }
}
