//@GeneratedCode
namespace QTPriceChecker.Logic.Controllers.App
{
    ///
    /// Generated by the generator
    ///
    public sealed partial class PriceHistoriesController : Controllers.GenericController<Entities.App.PriceHistory>, Contracts.App.IPriceHistoriesAccess<Entities.App.PriceHistory>
    {
        ///
        /// Generated by the generator
        ///
        static PriceHistoriesController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        ///
        /// Generated by the generator
        ///
        public PriceHistoriesController()
        {
            Constructing();
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public PriceHistoriesController(ControllerObject other)
        : base(other)
        {
            Constructing();
            Constructed();
        }
    }
}
