//@GeneratedCode
namespace QTPriceChecker.WebApi.Controllers.Base
{
    ///
    /// Generated by the generator
    ///
    public sealed partial class ProductXSuppliersController : Controllers.GenericController<QTPriceChecker.Logic.Entities.Base.ProductXSupplier, QTPriceChecker.WebApi.Models.Base.ProductXSupplierEdit, QTPriceChecker.WebApi.Models.Base.ProductXSupplier>
    {
        ///
        /// Generated by the generator
        ///
        static ProductXSuppliersController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        ///
        /// Generated by the generator
        ///
        public ProductXSuppliersController(QTPriceChecker.Logic.Contracts.Base.IProductXSuppliersAccess<QTPriceChecker.Logic.Entities.Base.ProductXSupplier> other)
        : base(other)
        {
            Constructing();
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        protected override QTPriceChecker.WebApi.Models.Base.ProductXSupplier ToOutModel(QTPriceChecker.Logic.Entities.Base.ProductXSupplier accessModel)
        {
            var handled = false;
            var result = default(QTPriceChecker.WebApi.Models.Base.ProductXSupplier);
            BeforeToOutModel(accessModel, ref result, ref handled);
            if (handled == false || result == null)
            {
                result = QTPriceChecker.WebApi.Models.Base.ProductXSupplier.Create(accessModel);
            }
            AfterToOutModel(result);
            return result;
        }
        partial void BeforeToOutModel(QTPriceChecker.Logic.Entities.Base.ProductXSupplier accessModel, ref QTPriceChecker.WebApi.Models.Base.ProductXSupplier? outModel, ref bool handled);
        partial void AfterToOutModel(QTPriceChecker.WebApi.Models.Base.ProductXSupplier outModel);
    }
}
