//@GeneratedCode
namespace QTPriceChecker.WebApi.Controllers.Base
{
    ///
    /// Generated by the generator
    ///
    public sealed partial class ProductsController : Controllers.GenericController<QTPriceChecker.Logic.Entities.Base.Product, QTPriceChecker.WebApi.Models.Base.ProductEdit, QTPriceChecker.WebApi.Models.Base.Product>
    {
        ///
        /// Generated by the generator
        ///
        static ProductsController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        ///
        /// Generated by the generator
        ///
        public ProductsController(QTPriceChecker.Logic.Contracts.Base.IProductsAccess<QTPriceChecker.Logic.Entities.Base.Product> other)
        : base(other)
        {
            Constructing();
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        protected override QTPriceChecker.WebApi.Models.Base.Product ToOutModel(QTPriceChecker.Logic.Entities.Base.Product accessModel)
        {
            var handled = false;
            var result = default(QTPriceChecker.WebApi.Models.Base.Product);
            BeforeToOutModel(accessModel, ref result, ref handled);
            if (handled == false || result == null)
            {
                result = QTPriceChecker.WebApi.Models.Base.Product.Create(accessModel);
            }
            AfterToOutModel(result);
            return result;
        }
        partial void BeforeToOutModel(QTPriceChecker.Logic.Entities.Base.Product accessModel, ref QTPriceChecker.WebApi.Models.Base.Product? outModel, ref bool handled);
        partial void AfterToOutModel(QTPriceChecker.WebApi.Models.Base.Product outModel);
    }
}
