//@GeneratedCode
namespace QTPriceChecker.Logic.DataContext
{
    ///
    /// Generated by the generator
    ///
    partial class ProjectDbContext
    {
        ///
        /// Generated by the generator
        ///
        public DbSet<QTPriceChecker.Logic.Entities.Base.Product>? ProductSet
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public DbSet<QTPriceChecker.Logic.Entities.Base.Supplier>? SupplierSet
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public DbSet<QTPriceChecker.Logic.Entities.Base.SupplierXProduct>? SupplierXProductSet
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public DbSet<QTPriceChecker.Logic.Entities.App.PriceHistory>? PriceHistorySet
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        partial void GetGeneratorDbSet<E>(ref DbSet<E>? dbSet, ref bool handled) where E : Entities.IdentityEntity
        {
            if (typeof(E) == typeof(QTPriceChecker.Logic.Entities.Base.Product))
            {
                dbSet = ProductSet as DbSet<E>;
                handled = true;
            }
            if (typeof(E) == typeof(QTPriceChecker.Logic.Entities.Base.Supplier))
            {
                dbSet = SupplierSet as DbSet<E>;
                handled = true;
            }
            if (typeof(E) == typeof(QTPriceChecker.Logic.Entities.Base.SupplierXProduct))
            {
                dbSet = SupplierXProductSet as DbSet<E>;
                handled = true;
            }
            if (typeof(E) == typeof(QTPriceChecker.Logic.Entities.App.PriceHistory))
            {
                dbSet = PriceHistorySet as DbSet<E>;
                handled = true;
            }
        }
    }
}
