//@GeneratedCode
namespace QTPriceChecker.AspMvc.Controllers.App
{
    using Microsoft.AspNetCore.Mvc;
    using TAccessModel = QTPriceChecker.Logic.Entities.App.PriceHistory;
    using TViewModel = QTPriceChecker.AspMvc.Models.App.PriceHistory;
    using TFilterModel = QTPriceChecker.AspMvc.Models.App.PriceHistoryFilter;
    using TAccessContract = QTPriceChecker.Logic.Contracts.App.IPriceHistoriesAccess<QTPriceChecker.Logic.Entities.App.PriceHistory>;
    ///
    /// Generated by the generator
    ///
    public sealed partial class PriceHistoriesController : Controllers.FilterGenericController<TAccessModel, TViewModel, TFilterModel, TAccessContract>
    {
        ///
        /// Generated by the generator
        ///
        static PriceHistoriesController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        protected override string ControllerName => "PriceHistories";
        ///
        /// Generated by the generator
        ///
        public PriceHistoriesController(QTPriceChecker.Logic.Contracts.App.IPriceHistoriesAccess<TAccessModel> other)
        : base(other)
        {
            Constructing();
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        protected override TViewModel ToViewModel(TAccessModel accessModel, ActionMode actionMode)
        {
            var handled = false;
            var result = default(TViewModel);
            BeforeToViewModel(accessModel, actionMode, ref result, ref handled);
            if (handled == false || result == null)
            {
                result = TViewModel.Create(accessModel);
            }
            AfterToViewModel(result, actionMode);
            return BeforeView(result, actionMode);
        }
        partial void BeforeToViewModel(TAccessModel accessModel, ActionMode actionMode, ref TViewModel? viewModel, ref bool handled);
        partial void AfterToViewModel(TViewModel viewModel, ActionMode actionMode);
    }
}
